name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Check Commits
        id: check-commits
        run: |
          # 获取昨天的时间戳
          yesterday=$(date -u -d "yesterday" +"%Y-%m-%dT00:00:00Z")
          
          # 获取昨天到现在的 commits
          commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/commits?since=$yesterday")

          # 过滤掉 commit message 为 'Generate Contribution Snake' 的 commit
          filtered_commits=$(echo "$commits" | jq '[.[] | select(.commit.message != "Generate Contribution Snake")]')

          # 判断是否有其他 commit
          if [ "$(echo $filtered_commits | jq length)" -eq "0" ]; then
            echo "前一天和今天未发现新的commit，或仅有'Generate Contribution Snake'的commit，暂时不更新Snake"
            echo "::set-output name=has-commits::false"
          else
            echo "发现前一天或今天有其他新的commit，更新Snake"
            echo "::set-output name=has-commits::true"
          fi

      - name: Generate Snake
        if: steps.check-commits.outputs.has-commits == 'true'
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub
        if: steps.check-commits.outputs.has-commits == 'true'
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: "Generate Contribution Snake"
